baseURL: https://uninotes.ryanbester.com/
languageCode: en-gb
title: University Notes
theme: hugo-book

menu:
  after:
    - name: Resources
      url: "https://github.com/ryanbester/uni-resources"

params:
  BookTheme: auto
  BookToC: true

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
